# Generated by Django 2.2.8 on 2020-01-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasting', '0008_auto_20151228_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='strength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='note',
            field=models.IntegerField(),
        ),
    ]
