# Generated by Django 2.2.8 on 2020-01-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuissonTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='hard',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='note',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparationTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=128),
        ),
    ]
